version: "3"
services:
    nginx:
        ports:
            - "80:80"
    game_app:
        build:
            context: ./app/
            args:
                NODE_ENV: production
        environment:
            - NODE_ENV=production
        command: node server.js
