version: "3"
services:
    nginx:
        build: ./nginx/
        ports:
            - "3000:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    game_app:
        build:
            context: ./app/
        environment:
            - PORT=3000
        depends_on:
            - nginx
